
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Contracts\HttpClient\HttpClientInterface:  '@http_client'
    Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.entity_manager'
    Psr\Log\LoggerInterface: '@monolog.logger.main'
    App\Interfaces\Transformers\PostTransformerInterface:
        class: App\Transformers\PostTransformer
    App\Interfaces\Repository\PostRepositoryInterface:
        class: App\Repository\PostRepository


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
